### ISSUE TITLE
Cannot run plugin

### ISSUE THREAD

**Issue by jahrralf** [JetBrains/phpstorm-phpstan-plugin#2]
Hi, I have installed the plugin and configured phpstan, however, phpstorm cannot run it:

16:56	PHPStan
			java.lang.IllegalArgumentException: Argument for @NotNull parameter 'parameter' of com/intellij/execution/configurations/GeneralCommandLine.addParameter must not be null
			Disable inspection

**Comment by jahrralf** [comment]
Wrong plugin installed...

**Comment by lexmes** [comment]
I have the same problem with PHPStorm PS-202.7319.77

**Comment by jdreesen** [comment]
You also installed the wrong plugin?

Else, see: #3

**Comment by lexmes** [comment]
How can i install the correct plugin? I installed it via the marketplace

**Comment by jdreesen** [comment]
Which one did you install? 
I doubt that this one is already on the marketplace because it's not released yet as it will only run with PhpStorm 2020.3 (which is also not released yet).

**Comment by lexmes** [comment]
Oh i'm sorry, you are right. I've installed this one: https://plugins.jetbrains.com/plugin/12754-phpstan--psalm--generics
I'll report there.
